# Generated by Django 5.2.5 on 2025-08-26 11:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_remove_category_slug'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='term',
            unique_together={('category', 'value')},
        ),
        migrations.RemoveField(
            model_name='term',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='term',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='term',
            name='first_letter',
        ),
        migrations.RemoveField(
            model_name='term',
            name='is_approved',
        ),
        migrations.RemoveField(
            model_name='term',
            name='normalized_value',
        ),
    ]
