# Generated by Django 5.2.5 on 2025-08-26 12:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_alter_term_unique_together_remove_term_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='highscore',
            name='last_updated',
        ),
    ]
